# Site settings
title: Title for site
email: email@email.email
description: >
  Description for site
baseurl: "/createive-theme-jekyll/" # the subpath of your site, e.g. /blog/
url: "https://ribab.github.io" # the base hostname & protocol for your site

#twitter_username:
#github_username:

# Build settings
markdown: kramdown
